import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F8FB",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: 30,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#166534",
    marginBottom: 12,
    letterSpacing: 0.2,
  },
  profileCard: {
    backgroundColor: "#fff",
    alignItems: "center",
    borderRadius: 18,
    paddingVertical: 30,
    paddingHorizontal: 18,
    marginTop: 8,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.09,
    shadowRadius: 10,
    elevation: 2,
    width: "100%",
    maxWidth: 370,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 100,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: "#E0E7EF",
    backgroundColor: "#E5E7EB",
  },
  name: {
    fontWeight: "bold",
    fontSize: 20,
    color: "#22223A",
    marginBottom: 2,
  },
  email: {
    fontSize: 15,
    color: "#64748B",
    marginBottom: 8,
  },
  roleBadge: {
    backgroundColor: "#ECFDF5",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 5,
    marginBottom: 12,
  },
  roleText: {
    color: "#16A34A",
    fontWeight: "bold",
    fontSize: 13,
    letterSpacing: 0.1,
  },
  infoContainer: {
    backgroundColor: "#F1F5F9",
    borderRadius: 10,
    flexDirection: "row",
    marginTop: 6,
    paddingVertical: 6,
    paddingHorizontal: 14,
    alignItems: "center",
    gap: 6,
  },
  infoLabel: {
    color: "#64748B",
    fontWeight: "600",
    fontSize: 14,
    marginRight: 4,
  },
  infoValue: {
    color: "#334155",
    fontWeight: "500",
    fontSize: 14,
  },
  logoutButton: {
    backgroundColor: '#fef2f2',
    marginTop: 22,
    width: 200,
    borderRadius: 12,
    height: 52,
    color: 'red',
    borderColor: '#a1a1aa',
    borderWidth: 2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: "center",
    flexDirection: 'row',
    gap: 8
  },

});
